// =============================================================================
// server/tools/pdf-generator.ts
// LINGORA SEEK 3.4 — PDF Generator Router
// =============================================================================
// Routes to the correct generator based on PDF type.
// NO S3 dependency for content generation.
// NO AWS dependency.
// Buffer → data URL (base64) for direct browser download.
//
// IS proposal accepted (SEEK 3.4):
//   "PDF not generated by tutor. Generated by fixed-template system."
//   "generatePDF() → buffer → direct download"
//   "S3/AWS: optional future — not required for seed"
//
// Two types:
//   lesson  → generateLessonPdf.ts  (Sara format: DEL 1-5 + bilingual table + fasit)
//   course  → generateCoursePdf.ts  (Zakia format: portada + módulos + cierre)
// =============================================================================

import { generateLessonPdf, LessonContent } from './generateLessonPdf';
import { generateCoursePdf, CourseContent }  from './generateCoursePdf';

// ── Storage (optional — S3 when configured, data URL fallback always works) ──
let uploadToS3: ((buf: Buffer, key: string, mime: string) => Promise<string | null>) | null = null;
try {
  // Lazy import — only active when S3_BUCKET env var is set
  if (process.env.S3_BUCKET) {
    const storageModule = require('./storage');
    uploadToS3 = storageModule.uploadToS3;
  }
} catch { /* S3 not configured — use data URL fallback */ }

// ── Public types ─────────────────────────────────────────────────────────────

export interface GeneratePDFParams {
  title: string;
  content: string;
  filename?: string;
  /** Structured content for typed generators */
  lessonContent?: LessonContent;
  courseContent?: CourseContent;
}

export interface GeneratePDFResult {
  success: boolean;
  url?: string;        // data URL (always) or S3 URL (when configured)
  method?: 'dataurl' | 's3';
  error?: string;
  message?: string;
}

// ── Router function (public API — execution-engine calls this) ────────────────

export async function generatePDF(params: GeneratePDFParams): Promise<GeneratePDFResult> {
  try {
    let pdfBytes: Uint8Array;

    // ── Route to structured generators when content is provided ──────────────
    if (params.lessonContent) {
      pdfBytes = await generateLessonPdf(params.lessonContent);
    } else if (params.courseContent) {
      pdfBytes = await generateCoursePdf(params.courseContent);
    } else {
      // ── Fallback: plain text PDF for chat export ──────────────────────────
      pdfBytes = await generatePlainTextPdf(params.title, params.content);
    }

    const buffer  = Buffer.from(pdfBytes);
    const key     = `pdfs/${params.filename ?? `lingora-${Date.now()}`}.pdf`;

    // Try S3 first (when configured), data URL fallback always available
    if (uploadToS3) {
      try {
        const s3Url = await uploadToS3(buffer, key, 'application/pdf');
        if (s3Url) return { success: true, url: s3Url, method: 's3' };
      } catch (s3Err) {
        console.warn('[pdf-generator] S3 upload failed, using data URL fallback:', s3Err);
      }
    }

    // Data URL fallback — always works, no infrastructure dependency
    const dataUrl = `data:application/pdf;base64,${buffer.toString('base64')}`;
    return { success: true, url: dataUrl, method: 'dataurl' };

  } catch (error: unknown) {
    const msg = error instanceof Error ? error.message : String(error);
    console.error('[pdf-generator] generation failed:', msg);
    return { success: false, error: 'generation_failed', message: msg };
  }
}

// ── Plain text PDF (chat export fallback) ─────────────────────────────────────
// Used when no structured content is available.
// Does NOT depend on S3. Generates immediately.
async function generatePlainTextPdf(title: string, content: string): Promise<Uint8Array> {
  const { PDFDocument, rgb, StandardFonts } = await import('pdf-lib');

  const doc    = await PDFDocument.create();
  const bold   = await doc.embedFont(StandardFonts.HelveticaBold);
  const regular = await doc.embedFont(StandardFonts.Helvetica);
  const page   = doc.addPage([595.28, 841.89]);
  const { height } = page.getSize();

  const NAVY   = rgb(0.05, 0.10, 0.16);
  const TEAL   = rgb(0.00, 0.79, 0.66);
  const DKGRAY = rgb(0.20, 0.25, 0.30);
  const MIDGRAY = rgb(0.78, 0.84, 0.90);
  const WHITE  = rgb(1, 1, 1);

  // Header
  page.drawRectangle({ x: 0, y: height - 56, width: 595.28, height: 56, color: NAVY });
  page.drawText('LINGORA', { x: 48, y: height - 34, size: 16, font: bold, color: WHITE });
  page.drawText(title.slice(0, 70), { x: 48, y: height - 50, size: 9, font: regular, color: TEAL });

  // Content
  const lines = String(content).split('\n');
  let y = height - 72;
  for (const rawLine of lines) {
    if (y < 40) break;
    const line = rawLine.slice(0, 88);
    const isHeader = line.startsWith('══') || line.startsWith('──');
    const isMentor = line.startsWith('◆');
    const isStudent = line.startsWith('▶');

    if (isHeader) {
      page.drawLine({ start: { x: 48, y: y - 4 }, end: { x: 548, y: y - 4 }, thickness: 0.5, color: TEAL });
      y -= 10;
      continue;
    }
    page.drawText(line, {
      x: 48, y,
      size: isMentor || isStudent ? 9.5 : 9,
      font: isMentor || isStudent ? bold : regular,
      color: isMentor ? NAVY : isStudent ? DKGRAY : DKGRAY,
    });
    y -= 13;
  }

  // Footer
  page.drawRectangle({ x: 0, y: 0, width: 595.28, height: 26, color: NAVY });
  page.drawText('lingora.netlify.app  ·  Exportado desde LINGORA', { x: 48, y: 9, size: 7.5, font: regular, color: MIDGRAY });

  return doc.save();
}
