// =============================================================================
// server/tools/pdf-generator.ts
// LINGORA SEEK 3.5 — PDF Generator Router
// =============================================================================
// Routes to the correct generator based on PDF type.
// NO S3 dependency for content generation.
// NO AWS dependency.
// Buffer → data URL (base64) for direct browser download.
//
// IS proposal accepted (SEEK 3.5):
//   "PDF not generated by tutor. Generated by fixed-template system."
//   "generatePDF() → buffer → direct download"
//   "S3/AWS: optional future — not required for seed".
//
// Two types:
//   lesson  → generateLessonPdf.ts  (Sara format: DEL 1-5 + bilingual table + fasit)
//   course  → generateCoursePdf.ts  (Zakia format: portada + módulos + cierre)
// =============================================================================

// NOTE: generateLessonPdf and generateCoursePdf use @sparticuz/chromium + puppeteer-core.
// These are loaded dynamically (lazy) so that chat export (plain text path)
// never triggers the chromium import — which would crash the module on Vercel
// if chromium is unavailable or times out on cold start.
// Dynamic imports are only executed when params.lessonContent or params.courseContent
// is explicitly provided by the caller (execution-engine tool_pdf steps).
import type { LessonContent } from './pdf/generateLessonPdf';
import type { CourseContent }  from './pdf/generateCoursePdf';

// ── Character sanitization — WinAnsi safe ───────────────────────────────────
// pdf-lib StandardFonts (Helvetica/HelveticaBold) use WinAnsi encoding.
// Characters outside WinAnsi (box-drawing, arrows, emoji) throw at drawText().
// Apply toPdfSafeText() to ALL dynamic strings before any page.drawText() call.
function toPdfSafeText(s: string, maxLen: number = 400): string {
  return String(s ?? '')
    .replace(/◆/g, '-')
    .replace(/▶/g, '>')
    .replace(/→/g, '->')
    .replace(/[–—]/g, '-')
    .replace(/[══]/g, '=')
    .replace(/[──]/g, '-')
    .replace(/💡/g, 'TIP')
    .replace(/[·]/g, '.')
    .replace(/[^ -~áéíóúüñ¿¡ÁÉÍÓÚÜÑàèìòùâêîôûçœæÀÈÌÒÙÂÊÎÔÛÇŒÆ]/g, ' ')
    .slice(0, maxLen);
}

// ── Storage (optional — S3 when configured, data URL fallback always works) ──
let uploadToS3: ((buf: Buffer, key: string, mime: string) => Promise<string | null>) | null = null;
try {
  // Lazy import — only active when S3_BUCKET env var is set
  if (process.env.S3_BUCKET) {
    const storageModule = require('./storage');
    uploadToS3 = storageModule.uploadToS3;
  }
} catch { /* S3 not configured — use data URL fallback */ }

// ── Public types ─────────────────────────────────────────────────────────────

export interface GeneratePDFParams {
  title: string;
  content: string;
  filename?: string;
  /** Structured content for typed generators */
  lessonContent?: LessonContent;
  courseContent?: CourseContent;
}

export interface GeneratePDFResult {
  success: boolean;
  url?: string;        // data URL (always) or S3 URL (when configured)
  method?: 'dataurl' | 's3';
  error?: string;
  message?: string;
}

// ── Router function (public API — execution-engine calls this) ────────────────

export async function generatePDF(params: GeneratePDFParams): Promise<GeneratePDFResult> {
  try {
    let pdfBytes: Uint8Array;

    // ── Route to structured generators when content is provided ──────────────
    if (params.lessonContent) {
      const { generateLessonPdf } = await import('./pdf/generateLessonPdf');
      pdfBytes = await generateLessonPdf(params.lessonContent);
    } else if (params.courseContent) {
      // SEEK 3.5: Use pdf-lib for CourseContent — avoids Puppeteer/Chromium timeout
      // on Vercel serverless (maxDuration 30s, OpenAI already consumes ~10s).
      // Puppeteer path preserved in generateCoursePdf.ts for future use with
      // longer timeout configuration or dedicated PDF service.
      pdfBytes = await generateCourseContentPdf(params.courseContent);
    } else {
      // ── Fallback: plain text PDF for chat export ──────────────────────────
      pdfBytes = await generatePlainTextPdf(params.title, params.content);
    }

    const buffer  = Buffer.from(pdfBytes);
    const key     = `pdfs/${params.filename ?? `lingora-${Date.now()}`}.pdf`;

    // Try S3 first (when configured), data URL fallback always available
    if (uploadToS3) {
      try {
        const s3Url = await uploadToS3(buffer, key, 'application/pdf');
        if (s3Url) return { success: true, url: s3Url, method: 's3' };
      } catch (s3Err) {
        console.warn('[pdf-generator] S3 upload failed, using data URL fallback:', s3Err);
      }
    }

    // Data URL fallback — always works, no infrastructure dependency
    const dataUrl = `data:application/pdf;base64,${buffer.toString('base64')}`;
    return { success: true, url: dataUrl, method: 'dataurl' };

  } catch (error: unknown) {
    const msg = error instanceof Error ? error.message : String(error);
    console.error('[pdf-generator] generation failed:', msg);
    return { success: false, error: 'generation_failed', message: msg };
  }
}


// ── Course PDF (pdf-lib — no Puppeteer/Chromium) ──────────────────────────────
// Renders CourseContent to a professional A4 PDF using pdf-lib only.
// Designed for Vercel serverless: no cold-start overhead, <1s generation.
// Layout: LINGORA header · course title · objective · modules · closing footer.
async function generateCourseContentPdf(
  course: import('./pdf/generateCoursePdf').CourseContent,
): Promise<Uint8Array> {
  const { PDFDocument, rgb, StandardFonts } = await import('pdf-lib');

  const NAVY    = rgb(0.05, 0.10, 0.16);
  const TEAL    = rgb(0.00, 0.79, 0.66);
  const WHITE   = rgb(1,    1,    1   );
  const DKGRAY  = rgb(0.20, 0.25, 0.30);
  const LTGRAY  = rgb(0.94, 0.96, 0.98);
  const MIDGRAY = rgb(0.78, 0.84, 0.90);
  const ACCENT  = rgb(0.08, 0.14, 0.25);

  const doc     = await PDFDocument.create();
  const bold    = await doc.embedFont(StandardFonts.HelveticaBold);
  const regular = await doc.embedFont(StandardFonts.Helvetica);

  const W = 595.28;
  const H = 841.89;
  const ML = 48;
  const MR = W - 48;
  const TW = MR - ML;

  // Helper: add a new page and return {page, y}
  function newPage(): { page: ReturnType<typeof doc.addPage>; y: number } {
    const page = doc.addPage([W, H]);
    // Header band
    page.drawRectangle({ x: 0, y: H - 46, width: W, height: 46, color: NAVY });
    page.drawText('LINGORA', { x: ML, y: H - 28, size: 13, font: bold, color: WHITE });
    page.drawText(
      toPdfSafeText(`${course.mentorName} - ${course.level} - ${course.courseTitle}`, 80),
      { x: ML, y: H - 40, size: 7.5, font: regular, color: TEAL }
    );
    // Footer band
    page.drawRectangle({ x: 0, y: 0, width: W, height: 24, color: NAVY });
    page.drawText(
      toPdfSafeText(`lingora.netlify.app - Learn -> Connect -> Experience - ${course.generatedAt}`, 120),
      { x: ML, y: 8, size: 7, font: regular, color: MIDGRAY }
    );
    return { page, y: H - 62 };
  }

  // Helper: safe text (truncate + strip non-latin safely)
  function safe(s: string, max = 90): string {
    return String(s ?? '').replace(/[^ -~áéíóúüñ¿¡ÁÉÍÓÚÜÑàèìòùâêîôûçœæÀÈÌÒÙÂÊÎÔÛÇŒÆ]/g, ' ').slice(0, max);
  }

  // Helper: draw wrapped text, returns new y
  function drawWrapped(
    page: ReturnType<typeof doc.addPage>,
    text: string,
    opts: { x: number; y: number; maxWidth: number; size: number; font: typeof bold; color: typeof NAVY; lineHeight?: number }
  ): number {
    const words = safe(text, 400).split(' ');
    const lh    = opts.lineHeight ?? opts.size * 1.45;
    let line    = '';
    let y       = opts.y;
    for (const word of words) {
      const test = line ? `${line} ${word}` : word;
      const w    = opts.font.widthOfTextAtSize(test, opts.size);
      if (w > opts.maxWidth && line) {
        page.drawText(line, { x: opts.x, y, size: opts.size, font: opts.font, color: opts.color });
        y -= lh;
        line = word;
      } else {
        line = test;
      }
    }
    if (line) {
      page.drawText(line, { x: opts.x, y, size: opts.size, font: opts.font, color: opts.color });
      y -= lh;
    }
    return y;
  }

  // ── COVER PAGE ────────────────────────────────────────────────────────────
  {
    const cover = doc.addPage([W, H]);
    // Full navy background
    cover.drawRectangle({ x: 0, y: 0, width: W, height: H, color: NAVY });
    // LINGORA brand
    cover.drawText('LINGORA', { x: ML, y: H - 80, size: 42, font: bold, color: WHITE });
    cover.drawText('AI Cultural Immersion Platform for Spanish', { x: ML, y: H - 104, size: 11, font: regular, color: TEAL });
    // Teal divider
    cover.drawRectangle({ x: ML, y: H - 120, width: TW, height: 2, color: TEAL });
    // Course title
    const title = safe(course.courseTitle, 70);
    cover.drawText(title, { x: ML, y: H - 160, size: 24, font: bold, color: WHITE });
    // Objective
    let oy = H - 200;
    oy = drawWrapped(cover, course.objective, { x: ML, y: oy, maxWidth: TW, size: 12, font: regular, color: MIDGRAY });
    // Meta grid
    const meta = [
      ['Nivel', course.level],
      ['Mentor', course.mentorName],
      ['Módulos', String(course.totalModules)],
      ['Idioma', course.nativeLanguage.toUpperCase()],
    ];
    let mx = ML; const my = oy - 30;
    for (const [k, v] of meta) {
      cover.drawRectangle({ x: mx, y: my - 36, width: 110, height: 36, color: ACCENT });
      cover.drawText(safe(k), { x: mx + 8, y: my - 16, size: 8, font: regular, color: TEAL });
      cover.drawText(safe(v, 14), { x: mx + 8, y: my - 30, size: 13, font: bold, color: WHITE });
      mx += 118;
    }
    // Footer
    cover.drawText('Learn -> Connect -> Experience', { x: ML, y: 40, size: 9, font: regular, color: TEAL });
    cover.drawText(toPdfSafeText(`lingora.netlify.app - ${course.generatedAt}`, 80), { x: ML, y: 26, size: 8, font: regular, color: MIDGRAY });
  }

  // ── MODULE PAGES ──────────────────────────────────────────────────────────
  for (const mod of (course.modules ?? [])) {
    let { page, y } = newPage();

    // Module band
    page.drawRectangle({ x: ML, y: y - 28, width: TW, height: 28, color: ACCENT });
    page.drawText(toPdfSafeText(`MODULO ${mod.index}`, 20), { x: ML + 8, y: y - 13, size: 8, font: bold, color: TEAL });
    page.drawText(safe(mod.title, 70), { x: ML + 8, y: y - 24, size: 13, font: bold, color: WHITE });
    y -= 44;

    // Vocabulary section
    page.drawText('VOCABULARIO', { x: ML, y, size: 8, font: bold, color: TEAL });
    y -= 14;
    const vocab = Array.isArray(mod.vocabulary) ? mod.vocabulary : [];
    for (let i = 0; i < vocab.length; i++) {
      const [word, def] = vocab[i] as [string, string];
      const rowBg = i % 2 === 0 ? LTGRAY : WHITE;
      page.drawRectangle({ x: ML, y: y - 14, width: TW, height: 16, color: rowBg });
      page.drawText(safe(word, 28), { x: ML + 6, y: y - 11, size: 9, font: bold, color: ACCENT });
      page.drawText(safe(def,  52), { x: ML + 160, y: y - 11, size: 9, font: regular, color: DKGRAY });
      y -= 16;
    }
    y -= 10;

    // Grammar
    page.drawRectangle({ x: ML, y: y - 30, width: TW, height: 30, color: LTGRAY });
    page.drawText('GRAMÁTICA 80/20', { x: ML + 8, y: y - 10, size: 8, font: bold, color: TEAL });
    y = drawWrapped(page, mod.grammar, { x: ML + 8, y: y - 20, maxWidth: TW - 16, size: 9.5, font: regular, color: DKGRAY });
    y -= 10;

    // Exercise
    page.drawText('EJERCICIO', { x: ML, y, size: 8, font: bold, color: TEAL });
    y -= 12;
    y = drawWrapped(page, mod.exercise, { x: ML, y, maxWidth: TW, size: 10, font: regular, color: DKGRAY });
    // Answer line
    page.drawLine({ start: { x: ML, y: y - 8 }, end: { x: MR, y: y - 8 }, thickness: 0.5, color: MIDGRAY });
    y -= 24;

    // Communicative function
    page.drawRectangle({ x: ML, y: y - 24, width: 4, height: 24, color: TEAL });
    page.drawText('PUEDES HACER:', { x: ML + 10, y, size: 7.5, font: bold, color: TEAL });
    y = drawWrapped(page, mod.communicativeFunction, { x: ML + 10, y: y - 12, maxWidth: TW - 10, size: 9.5, font: regular, color: DKGRAY });
    y -= 8;

    // Tip
    page.drawRectangle({ x: ML, y: y - 28, width: TW, height: 28, color: ACCENT });
    page.drawText('TIP  CONSEJO', { x: ML + 8, y: y - 10, size: 8, font: bold, color: TEAL });
    y = drawWrapped(page, mod.tip, { x: ML + 8, y: y - 20, maxWidth: TW - 16, size: 9, font: regular, color: MIDGRAY });
  }

  // ── CLOSING PAGE ──────────────────────────────────────────────────────────
  {
    let { page, y } = newPage();
    page.drawText('PRÓXIMOS PASOS', { x: ML, y, size: 14, font: bold, color: NAVY });
    y -= 20;
    page.drawRectangle({ x: ML, y: y - 4, width: 60, height: 3, color: TEAL });
    y -= 20;
    y = drawWrapped(page, course.nextStep, { x: ML, y, maxWidth: TW, size: 11, font: regular, color: DKGRAY });
    y -= 20;
    const summary = [
      ['Módulos completados', String(course.totalModules)],
      ['Nivel', course.level],
      ['Mentor', course.mentorName],
      ['Estudiante', course.studentName],
    ];
    for (const [k, v] of summary) {
      page.drawText(`${safe(k)}:`, { x: ML, y, size: 9, font: bold, color: NAVY });
      page.drawText(safe(v, 30), { x: ML + 140, y, size: 9, font: regular, color: DKGRAY });
      y -= 16;
    }
  }

  return doc.save();
}

// ── Plain text PDF (chat export fallback) ─────────────────────────────────────
// Used when no structured content is available.
// Does NOT depend on S3. Generates immediately.
async function generatePlainTextPdf(title: string, content: string): Promise<Uint8Array> {
  const { PDFDocument, rgb, StandardFonts } = await import('pdf-lib');

  const doc    = await PDFDocument.create();
  const bold   = await doc.embedFont(StandardFonts.HelveticaBold);
  const regular = await doc.embedFont(StandardFonts.Helvetica);
  const page   = doc.addPage([595.28, 841.89]);
  const { height } = page.getSize();

  const NAVY   = rgb(0.05, 0.10, 0.16);
  const TEAL   = rgb(0.00, 0.79, 0.66);
  const DKGRAY = rgb(0.20, 0.25, 0.30);
  const MIDGRAY = rgb(0.78, 0.84, 0.90);
  const WHITE  = rgb(1, 1, 1);

  // Header
  page.drawRectangle({ x: 0, y: height - 56, width: 595.28, height: 56, color: NAVY });
  page.drawText('LINGORA', { x: 48, y: height - 34, size: 16, font: bold, color: WHITE });
  page.drawText(toPdfSafeText(title, 70), { x: 48, y: height - 50, size: 9, font: regular, color: TEAL });

  // Content
  const lines = String(content).split('\n');
  let y = height - 72;
  for (const rawLine of lines) {
    if (y < 40) break;
    const line = rawLine.slice(0, 88);
    const isHeader = line.startsWith('══') || line.startsWith('──');
    const isMentor = line.startsWith('◆');
    const isStudent = line.startsWith('▶');

    if (isHeader) {
      page.drawLine({ start: { x: 48, y: y - 4 }, end: { x: 548, y: y - 4 }, thickness: 0.5, color: TEAL });
      y -= 10;
      continue;
    }
    page.drawText(toPdfSafeText(line, 88), {
      x: 48, y,
      size: isMentor || isStudent ? 9.5 : 9,
      font: isMentor || isStudent ? bold : regular,
      color: isMentor ? NAVY : isStudent ? DKGRAY : DKGRAY,
    });
    y -= 13;
  }

  // Footer
  page.drawRectangle({ x: 0, y: 0, width: 595.28, height: 26, color: NAVY });
  page.drawText('lingora.netlify.app - Exportado desde LINGORA', { x: 48, y: 9, size: 7.5, font: regular, color: MIDGRAY });

  return doc.save();
}

